/*
 * advanced-material-web — Material 3 web components
 * Copyright (c) 2017-2026 Mikhail Podgurskiy
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * AGPLv3 with the Viewflow Library Exception — see LICENSE_EXCEPTION.
 *
 * The copyright holder regards code produced from this file with an LLM's
 * help as a derived work: placing it in a model's context is copying it.
 * A commercial licence without copyleft: https://viewflow.io/pro.html
 */

/**
 * Public surface of advanced-material-web's ./angular subpath.
 *
 * Everything under ./lib is generated by the Stencil build — see
 * `angularOutputTarget` in stencil.config.ts. This file is not.
 */
export * from './lib/components';
export { DIRECTIVES } from './lib/index';

export { ValueAccessor } from './lib/value-accessor';
export { BooleanValueAccessor } from './lib/boolean-value-accessor';
export { NumericValueAccessor } from './lib/number-value-accessor';
export { RadioValueAccessor } from './lib/radio-value-accessor';
export { TextValueAccessor } from './lib/text-value-accessor';
